name: Build, Push & Deploy Laravel Octane (Swoole)

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, k8s, ctf]

    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
      DEPLOYMENT_NAME: ${{ secrets.K8S_DEPLOYMENT_NAME }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract version tag
        id: vars
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          VERSION_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo ${BRANCH}-${COMMIT})
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Resolved VERSION_TAG=$VERSION_TAG"

      - name: Build & Push image using Makefile
        run: |
          make build-image IMAGE_NAME=${{ secrets.IMAGE_NAME }}
          make push-image IMAGE_NAME=${{ secrets.IMAGE_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update K8s Deployment with new image
        run: |
          kubectl -n $K8S_NAMESPACE set image deployment/$K8S_DEPLOYMENT_NAME app=${{ secrets.IMAGE_NAME }}:${{ env.VERSION_TAG }}
          kubectl -n $K8S_NAMESPACE rollout status deployment/$K8S_DEPLOYMENT_NAME --timeout=180s
